[package]
name = "hdb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
libc = "0.2.176"
reedline = "0.42.0"
thiserror = "2.0.17"

[dev-dependencies]
tempfile = "3.23.0"
